### ISSUE TITLE
Everyone to contribute

### ISSUE THREAD

**Issue by winpom** [IntroToCode/RecipesCodemates1#11]
## 💬 Discussion topic

We need everyone to contribute to every recipe

## ❗ Potential issues

I'm not certain if everyone has, and I don't know how to check

## 👥 People to consult

@soniyaparmar08 
@wkellogg 
@hiro-in-berkeley 
@sochoteco 

## 📃 Details

We also needed to make issues, so here's the first!

**Comment by sochoteco** [comment]
I am contributing - thank you

**Comment by sochoteco** [comment]
Looks that everyone is contributing now
